name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Initialize local environment
      run: deno task dev

    - name: Run tests
      run: cargo test
